### PR TITLE
Export liked albums in addition to liked songs

### PR DESCRIPTION
**Pull request by peterrus**
Implements request from #19

### CODE REVIEW

**Review by AtomicNess123 — APPROVED** [review]

**Comment by peterrus** [comment]
@AtomicNess123 If you feel like testing it out I am happy to know if it works for you!

**Comment by AtomicNess123** [comment]
> @AtomicNess123 If you feel like testing it out I am happy to know if it works for you!

[I did but did not work :( ](https://github.com/caseychu/spotify-backup/issues/19#issuecomment-1074808969)

**Comment by peterrus** [comment]
@AtomicNess123 how did you call the script? The default (without parameters) does indeed not export the liked songs. You have to call it like:

```
python spotify-backup.py playlists.txt --dump=liked,playlists
```

(or just with `liked` if you dont care about the playlists)

**Comment by AtomicNess123** [comment]
Apologies, did not read the README.md for the syntax. It works!

**Comment by caseychu** [comment]
Thanks for the PR!

**Pull request merged**
